#!/usr/bin/env -S node
const url = require('node:url');

(async () => {
  const metaUrl = url.pathToFileURL(__filename).href;  
  const { execute } = await import('@oclif/core');
  await execute({ dir: metaUrl });
})();
